config_metadata: 'Saving time : 03/16/2024, 18:43:22'

# data options
data:
    path: 'data/data_labo'
    real_data_path: data/data_real
    image_size: 256
    num_classes: 18
    background_classes: 4
    transforms:
        run_rotation: false
        run_hflip: true
        run_vflip: true
        color:
            brightness: 2
            contrast: 2
            saturation: 0.0
            hue: 0.0

# model options
model:
    name: 'adversarial'
    resnet:
        hidden_size: 64
        p_dropout: 0.1
        freeze_resnet: false
        resume_training:
            do_resume: false
            path: 'logs/resnet_7'
            freeze_param: false
    adversarial:
        hidden_size: 256
        p_dropout: 0.1

# learning options
learning:
    epochs: 2
    batch_size: 8
    learning_rate: 0.01
    shuffle: true
    drop_last: true
    device: 'cuda'
    save_experiment: true
    save_checkpoint: true
    loss: 'crossentropy'
    optimizer: 'adam'
    num_workers: 1
    adv:
        learning_rate_adversary: 0.001
        alpha: 10

# test options
test:
    batch_size: 244
    shuffle: true
    drop_last: true
    device: 'cuda'
    num_workers: 1
