config_metadata: 'Saving time : 03/17/2024, 21:17:25'
config_metadata: 'Saving time : 03/17/2024, 20:20:02'

# data options
data:
    path: 'data/data_labo'
    real_data_path: 'data/data_real'
    image_size: 256
    num_classes: 18
    background_classes: 4
    transforms:
        run_rotation: false
        run_hflip: true
        run_vflip: true
        color:
            brightness: 2
            contrast: 2
            saturation: 0.0
            hue: 0.0

# model options
model:
    name: 'adversarial'
    resnet:
        hidden_size: 64
        p_dropout: 0.1
        freeze_resnet: true
        resume_training:
            do_resume: false
            path: 'logs/resnet_7'
            freeze_param: false
    adversarial:
        hidden_size: 256
        p_dropout: 0.1

# learning options
learning:
    epochs: 20
    batch_size: 42
    learning_rate: 0.005
    loss: 'crossentropy'
    optimizer: 'adam'
    device: 'cuda'
    num_workers: 1
    shuffle: true
    drop_last: true
    save_experiment: true
    save_checkpoint: true
    plot_learning_curves: true
    adv:
        learning_rate_adversary: 0.0001
        alpha: 0.1

# test options
test:
    batch_size: 244
    device: 'cuda'
    num_workers: 1
    shuffle: true
    drop_last: true
