#learning:
#  learning_rate: [0.1, 0.01, 0.001, 0.0001]
#  dann:
#    learning_rate_adversary: [0.1, 0.01, 0.001, 0.0001]
#    Lambda: [0.001, 0.01, 0.1, 1, 10]

#learning:
#  learning_rate: [0.1, 0.01, 0.001, 0.005, 0.0001]
#  dann:
#    learning_rate_adversary: [0.1, 0.01, 0.001, 0.005, 0.0001]
#    Lambda: [0.001, 0.01, 0.1, 0.5, 1, 10]

learning:
  learning_rate: [ 0.0001]
  freeze_backbone: [false,true]
  freeze_param: [false,true]
  batch_size: [64,42,32]