data:                                 # data parameters
  path: data/data_labo                # path to the data
  real_data_path: data/data_real      # path to the real data
  image_size: 256                     # size of the images
  num_classes: 18                     # number of classes                  
  background_classes: 4               # number of background classes      
  transforms:                         # data augmentation           
    run_rotation: false               # rotation       
    run_hflip: true                   # horizontal flip           
    run_vflip: true                   # vertical flip      
    color:                            # color augmentation     
      brightness: 2                   # brightness
      contrast: 2                     # contrast                           
      saturation: 0.0                 # saturation
      hue: 0.0                        # hue

model:                                # model parameters
  name: adversarial                        # name of the model. can be resnet, adversarial
  resnet:                             # resnet parameters
    hidden_size: 64                   # hidden size of the resnet
    p_dropout: 0.1                    # dropout probability
    freeze_resnet: true              # freeze the convolution layer of the resnet
    resume_training:                  # resume training from an experiment
      do_resume: false                # do resume training
      path: logs/resnet_7             # path to the experiment
      freeze_param: false             # freeze the parameters for this experiment
  adversarial:                        # adversarial parameters
    hidden_size: 256                  # hidden size of the adversarial model
    p_dropout: 0.1                    # dropout probability

learning:                             # learning parameters (training and validation)
  epochs: 5                           # number of epochs
  batch_size: 42                      # batch size
  learning_rate: 0.0001               # learning rate
  loss: crossentropy                  # loss function
  optimizer: adam                     # optimizer
  device: cuda                        # device
  num_workers: 1                      # number of workers 
  shuffle: true                       # shuffle the data
  drop_last: true                     # drop the last batch
  save_experiment: true               # save the experiment
  save_checkpoint: true               # save the checkpoint
  plot_learning_curves: true          # plot the learning curves
  adv:                                # adversarial parameters
    learning_rate_adversary: 0.0001   # learning rate of the adversary
    alpha: 10                         # coeficient of the adversarial loss: resnet_loss / (alpha * adversary_loss)

test:                                 # test parameters
  batch_size: 244                     # batch size
  device: cuda                        # device
  num_workers: 1                      # number of workers
  shuffle: true                       # shuffle the data
  drop_last: true                     # drop the last batch
