config_metadata: 'Saving time : 03/09/2024, 17:57:43'

# data options
data:
    path: 'data/data_labo'
    image_size: 256
    num_classes: 18
    background_classes: 4
    transforms:
        run_rotation: false
        run_hflip: true
        run_vflip: true
        color:
            brightness: 2
            contrast: 2
            saturation: 0.0
            hue: 0.0

# model options
model:
    name: 'resnet'
    resnet:
        hidden_size: 64
        p_dropout: 0.1
        freeze_resnet: true
        resume_training:
            do_resume: false
            path: 'logs/resnet_7'
            freeze_param: false
    adversarial:
        hidden_size: 256
        p_dropout: 0.1

# learning options
learning:
    epochs: 5
    batch_size: 8
    learning_rate: 0.0001
    learning_rate_adversary: 0.001
    shuffle: true
    drop_last: true
    device: 'cuda'
    save_experiment: true
    save_checkpoint: true
    loss: 'crossentropy'
    num_workers: 4
    alpha: 10
